### ISSUE TITLE
Autocorrect

### ISSUE THREAD

**Issue by JulianSampels** [JulianSampels/OntoMatch#10]
I'm not sure if the autocorrect is correcting things in a good way:
![image](https://github.com/JulianSampels/OntoMatch/assets/153213878/ec81253c-7422-4f62-bad9-18de5e24181e)
there is also a spell_check function in https://github.com/JulianSampels/OntoMatch/blob/386baa7788070bd95fe9d9df81df3027b0c52289/src/batch_loaders/ontology_parsing/preprocessing.py#L95
but this is not used, maybe because of the problems with multiple words without spaces

**Comment by sefeoglu** [comment]
I did not implemented it. It was from previous work. I just call the spell in lowercase function.
Here is my line:

<img width="1089" alt="Screenshot 2024-05-03 at 16 01 00" src="https://github.com/JulianSampels/OntoMatch/assets/4726002/844231bf-e180-4542-b319-41c09d47ee47">

**Comment by sefeoglu** [comment]
I will try to fix it.

**Comment by JulianSampels** [comment]
it was there before, but I think not used because of the same problem

**Comment by sefeoglu** [comment]
Here is the new exact matching result with 1.0 threshold:
<img width="1293" alt="Screenshot 2024-05-03 at 16 04 14" src="https://github.com/JulianSampels/OntoMatch/assets/4726002/57a98d49-c952-40a4-ad9a-0b7e5606f6b6">
