### ISSUE TITLE
run_matcher.py fails

### ISSUE THREAD

**Issue by FelixFrizzy** [JulianSampels/OntoMatch#19]
I'm trying to execute ontomatch, but i fail.

Steps to reproduce:

- MacOS Sonoma 14.4
- python 3.12.4
- pip3 install -r requirements.txt
- download and extract val_avg_bleu=68.1000-step_count=5.ckpt to src/verbalizer/graph2text/outputs/t5-base_13881/
- cd src
- python3 run_matcher.py
- get error message

It uses the default dataset, I didn't include my own. This time it is not related to (missing or faulty) python packages I guess, but rather to problems in the code base itself. Do you have any ideas how to fix it? It would be great if you keep the issue open until it's fixed, I am interested in running it also after OAEI has finished. 

```
Verbalizing:   0%|          | 0/71 [00:00<?, ?item/s]
['translate Graph to English: <H> event <R> is parent of <T> scientificevent <H> scientificevent <R> is parent of <T> individualpresentation <H> individualpresentation <R> is parent of <T> contributedtalk  <H> event <R> is parent of <T> socialevent <H> socialevent <R> is parent of <T> conferencetrip ']
ERROR VERBALISING translate Graph to English: <H> event <R> is parent of <T> scientificevent <H> scientificevent <R> is parent of <T> individualpresentation <H> individualpresentation <R> is parent of <T> contributedtalk  <H> event <R> is parent of <T> socialevent <H> socialevent <R> is parent of <T> conferencetrip 
Traceback (most recent call last):
  File "...OntoMatch/src/run_matcher.py", line 362, in <module>
    main()
  File "...OntoMatch/src/run_matcher.py", line 223, in main
    tripleVerbalizer.verbaliseFile(tripleFilePath, tripleVerbalizedFilePath)
  File "...OntoMatch/src/verbalizer/tripleVerbalizer.py", line 33, in verbaliseFile
    verbalised_text = verbalise(triples, verb_module)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...OntoMatch/src/verbalizer/tripleVerbalizer.py", line 16, in verbalise
    return verbModule.verbalise(ans)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...OntoMatch/src/verbalizer/verbalisation_module.py", line 143, in verbalise
    return self.verbalise_sentence(input)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...OntoMatch/src/verbalizer/verbalisation_module.py", line 103, in verbalise_sentence
    gen_output = self.__generate_verbalisations_from_inputs(inputs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...OntoMatch/src/verbalizer/verbalisation_module.py", line 46, in __generate_verbalisations_from_inputs
    gen_output = self.g2t_module.model.generate(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.virtualenvs/ontomatch/lib/python3.12/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/username/.virtualenvs/ontomatch/lib/python3.12/site-packages/transformers/generation/utils.py", line 1713, in generate
    self._prepare_special_tokens(generation_config, kwargs_has_attention_mask, device=device)
  File "/Users/username/.virtualenvs/ontomatch/lib/python3.12/site-packages/transformers/generation/utils.py", line 1556, in _prepare_special_tokens
    raise ValueError(
ValueError: `decoder_start_token_id` or `bos_token_id` has to be defined for encoder-decoder generation.
```

**Comment by JulianSampels** [comment]
Perhaps this is caused by using a different module version.  Which version of `transformers` are you using? Please run `pip show transformers`.

**Comment by FelixFrizzy** [comment]
I use 4.44.2. The minimal version of the requirements is 1.0.1 (which is 5 years old). Could you update the requirements file (maybe for now in a seperate branch) with all the packages that you really use including versions? more or less exactly what `pip freeze` would give you, so only `==` relations for package version numbers. then i can try again.

**Comment by huanyu-li** [comment]
Hi Julian,

I have the same problem when running from a fresh python environment and install from the requirements.
The installed transformers  has version of 4.45.1.

/Huanyu

**Comment by JulianSampels** [comment]
I am sorry for the inconvenience. Hopefully, the specific requirements provided in commit 976d3ae801d42a125ae1b476b145cb33d582055f on the branch [specificRequirements](https://github.com/JulianSampels/OntoMatch/tree/specificRequirements) will help in investigating the problem further. Please let me know if the problems still persist.

**Comment by FelixFrizzy** [comment]
I can suceessfully run the tool (with the added step from the PR #20 ) using commit 976d3ae

**Comment by huanyu-li** [comment]
Hi Julian, I just want to ask if you also ran your system for anatomy track. It has been running more than hours for me. I wonder if you have specific config for other tracks than conference track. /Huanyu

**Comment by JulianSampels** [comment]
Hi Huanyu, 
have you tried it on the old [experiment/anatomy-dataset](https://github.com/JulianSampels/OntoMatch/tree/experiment/anatomy-dataset) branch? The old branch has some known performance limitations, mainly due to computing unnecessary prompts. I am currently working on improving it in the [experiment/anatomy-dataset2](https://github.com/JulianSampels/OntoMatch/tree/experiment/anatomy-dataset2) branch, but please note that I can't fully guarantee it will work perfectly yet. 

Let me know if you run into any issues or need help!
